// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubzXo0TAtQnQP4XcGAu7RLpkd-nrDg4I',
    appId: '1:307354088058:web:ee10d84a8e76e485a741c3',
    messagingSenderId: '307354088058',
    projectId: 'nulook-57c3a',
    authDomain: 'nulook-57c3a.firebaseapp.com',
    storageBucket: 'nulook-57c3a.firebasestorage.app',
    measurementId: 'G-SE4FQZME4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiYfvGvTxME5T6TndIcy0O4nkkyPGuqOU',
    appId: '1:307354088058:android:45ec95cddd59c0daa741c3',
    messagingSenderId: '307354088058',
    projectId: 'nulook-57c3a',
    storageBucket: 'nulook-57c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtpi8-XeEHysfp54nO1pACQnoQtWVUaP4',
    appId: '1:307354088058:ios:23b889496f79b6c1a741c3',
    messagingSenderId: '307354088058',
    projectId: 'nulook-57c3a',
    storageBucket: 'nulook-57c3a.firebasestorage.app',
    iosBundleId: 'com.affluora.nulookapp',
  );
}
